######################################################################
# Automatically generated by qmake (3.0) Wed Aug 21 15:56:12 2019
######################################################################

QT += widgets
TEMPLATE = app
TARGET = exec03
INCLUDEPATH += .

# Input
SOURCES += exec03.cpp
