######################################################################
# Automatically generated by qmake (3.0) Wed Aug 21 17:06:42 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec04
INCLUDEPATH += .

# Input
SOURCES += exec04.cpp
