######################################################################
# Automatically generated by qmake (3.0) Fri Aug 23 13:28:05 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec02
INCLUDEPATH += .

# Input
HEADERS += Time.h ui_Time.h
FORMS += Time.ui
SOURCES += main.cpp Time.cpp
