######################################################################
# Automatically generated by qmake (3.0) Thu Aug 22 21:43:11 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec06
INCLUDEPATH += .

# Input
HEADERS += MyTextBrowser.h
SOURCES += exec06.cpp MyTextBrowser.cpp
