######################################################################
# Automatically generated by qmake (3.0) Wed Aug 21 11:00:07 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec01
INCLUDEPATH += .

# Input
SOURCES += exec01.cpp
