######################################################################
# Automatically generated by qmake (3.0) Fri Aug 23 14:47:52 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec03
INCLUDEPATH += .

# Input
HEADERS += LoginDlg.h ui_Login.h
FORMS += Login.ui
SOURCES += LoginDlg.cpp main.cpp
