######################################################################
# Automatically generated by qmake (3.0) Wed Aug 21 11:44:42 2019
######################################################################
QT += widgets
QT += core
TEMPLATE = app
TARGET = exec02
INCLUDEPATH += .

# Input
SOURCES += exec02.cpp
