######################################################################
# Automatically generated by qmake (3.0) Fri Aug 23 10:05:31 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec01
INCLUDEPATH += .

# Input
HEADERS += CalDlg.h ui_CalDlg.h
FORMS += CalDlg.ui
SOURCES += CalDlg.cpp main.cpp
