######################################################################
# Automatically generated by qmake (3.0) Thu Aug 22 11:41:56 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec01
INCLUDEPATH += .

# Input
HEADERS += CalDlg.h
SOURCES += CalDlg.cpp main.cpp
