######################################################################
# Automatically generated by qmake (3.0) Thu Aug 22 19:04:45 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec04
INCLUDEPATH += .

# Input
HEADERS += ui_CalDlg.h
FORMS += untitled.ui
SOURCES += exec04.cpp
