######################################################################
# Automatically generated by qmake (3.0) Thu Aug 22 20:09:53 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec02
INCLUDEPATH += .

# Input
HEADERS += Clock.h
SOURCES += Clock.cpp main.cpp
