######################################################################
# Automatically generated by qmake (3.0) Thu Aug 22 16:11:23 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = exec03
INCLUDEPATH += .

# Input
HEADERS += TimeDlg.h
SOURCES += main.cpp TimeDlg.cpp
